ALTER TABLE habits ADD COLUMN IF NOT EXISTS identity_label VARCHAR(100) DEFAULT '';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS revival_tokens INTEGER DEFAULT 2;
ALTER TABLE habits ADD COLUMN IF NOT EXISTS revival_month VARCHAR(7) DEFAULT '';
ALTER TABLE habit_completions ADD COLUMN IF NOT EXISTS identity_score INTEGER;
