-- Migration 032: Unified journal capture + review layers
--
-- daily_entries is the new source of truth for day-level journal capture.
-- Themed journals are filtered views of this table via tags.
-- weekly_reviews and monthly_compasses store synthesis layers that can be
-- generated by Lumi and edited independently by the user.

CREATE TABLE IF NOT EXISTS daily_entries (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    entry_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    entry_type     VARCHAR(40) NOT NULL DEFAULT 'daily',
    template_type  VARCHAR(100) NOT NULL DEFAULT 'Classic Diary',
    title          TEXT,
    entry_text     TEXT NOT NULL DEFAULT '',
    tags           TEXT[] NOT NULL DEFAULT ARRAY['personal']::TEXT[],
    fields         JSONB NOT NULL DEFAULT '{}',
    attachments    JSONB NOT NULL DEFAULT '[]',
    stickers       JSONB NOT NULL DEFAULT '[]',
    source         VARCHAR(20) NOT NULL DEFAULT 'user',

    archived_at    TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_entries_user_date
    ON daily_entries(user_id, entry_date DESC, created_at DESC)
    WHERE archived_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_daily_entries_user_tags
    ON daily_entries USING GIN (tags);

CREATE INDEX IF NOT EXISTS idx_daily_entries_user_fields
    ON daily_entries USING GIN (fields);

ALTER TABLE daily_entries ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'daily_entries_user_isolation'
    ) THEN
        CREATE POLICY daily_entries_user_isolation ON daily_entries
        FOR ALL USING (user_id = current_setting('app.current_user_id')::UUID);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'update_daily_entries_updated_at'
    ) THEN
        CREATE TRIGGER update_daily_entries_updated_at
        BEFORE UPDATE ON daily_entries
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS weekly_reviews (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id              UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    week_start           DATE NOT NULL,
    ai_summary           TEXT,
    user_notes           TEXT,
    wins                 TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    struggles            TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    learning             TEXT,
    next_week_intention  TEXT,
    fields               JSONB NOT NULL DEFAULT '{}',
    attachments           JSONB NOT NULL DEFAULT '[]',
    stickers              JSONB NOT NULL DEFAULT '[]',
    source               VARCHAR(20) NOT NULL DEFAULT 'user',
    archived_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (user_id, week_start)
);

CREATE INDEX IF NOT EXISTS idx_weekly_reviews_user_week
    ON weekly_reviews(user_id, week_start DESC)
    WHERE archived_at IS NULL;

ALTER TABLE weekly_reviews ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'weekly_reviews_user_isolation'
    ) THEN
        CREATE POLICY weekly_reviews_user_isolation ON weekly_reviews
        FOR ALL USING (user_id = current_setting('app.current_user_id')::UUID);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'update_weekly_reviews_updated_at'
    ) THEN
        CREATE TRIGGER update_weekly_reviews_updated_at
        BEFORE UPDATE ON weekly_reviews
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS monthly_compasses (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    month_start    DATE NOT NULL,
    theme          TEXT,
    goals          JSONB NOT NULL DEFAULT '[]',
    achievements   TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    lessons        TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    review         TEXT,
    cover_image    TEXT,
    fields         JSONB NOT NULL DEFAULT '{}',
    attachments    JSONB NOT NULL DEFAULT '[]',
    stickers       JSONB NOT NULL DEFAULT '[]',
    source         VARCHAR(20) NOT NULL DEFAULT 'user',
    archived_at    TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (user_id, month_start)
);

CREATE INDEX IF NOT EXISTS idx_monthly_compasses_user_month
    ON monthly_compasses(user_id, month_start DESC)
    WHERE archived_at IS NULL;

ALTER TABLE monthly_compasses ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'monthly_compasses_user_isolation'
    ) THEN
        CREATE POLICY monthly_compasses_user_isolation ON monthly_compasses
        FOR ALL USING (user_id = current_setting('app.current_user_id')::UUID);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'update_monthly_compasses_updated_at'
    ) THEN
        CREATE TRIGGER update_monthly_compasses_updated_at
        BEFORE UPDATE ON monthly_compasses
        FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;
